### PR TITLE
Fix for sapling

### PR DESCRIPTION
**Pull request by okoto-xyz**
バージョンの読み込み処理と、finalsaplinghashの位置を修正しました。

### CODE REVIEW

**Comment by wo01** [comment]
あぁ，stringそのまま変換になるからbeですね．ありがとうございます

**Comment by solardiz** [comment]
Is this PR based only on code review or also on actual testing?

I am wondering if only getblocktemplate or also stratum have been tested with Koto's implementation of Sapling.

Are there any mining pools supporting this protocol? Which ones?

**Comment by solardiz** [comment]
Per my code review, there are two uses of `memcmp` in `miner_thread`, which haven't been updated to take account of `finalsaplinghash`. But perhaps they don't need to? (They compare only the first 76 bytes of header. To also compare that extra hash given Koto's block header layout, yet ignore the nonce, it'd take pairs of `memcmp` per check - one of 76 and the other of 32 bytes.)

**Comment by wo01** [comment]
Koto testnet already have activated Sapling.
We have tested on the testnet and it works for now.
Testnet pool is available  at http://51.15.229.223:8080/

Oh, strictly thinking we need to compare 76 + 32 bytes.

**Comment by solardiz** [comment]
Thanks @wo01. Has your project's team tested both getblocktemplate and stratum, or only one of them (which one)?

**Comment by wo01** [comment]
Yes, we have tested GBT and stratum.

**Comment by solardiz** [comment]
Great. Is your choice to add `finalsaplinghash` as parameter 9 in stratum Koto-specific or is the same choice also made elsewhere? What software do you use to implement the mining pool, and how does it know to speak this protocol revision?

I tried searching for info on how Zcash recommended to handle this field in stratum, but found only what I already knew - that it's merely reuse of their previously reserved field. Patches like seen in https://github.com/s-nomp/node-stratum-pool/commit/3daad16084d3ab20ca4a09bb228e77e6c18e6650 do in fact merely reuse that field, so perhaps it was already being communicated over the protocol before, despite of it being reserved?

I understand that it's different for Koto because you had previously omitted the field to have the standard 80-byte header.

**Comment by wo01** [comment]
This solution is the Koto-specific, and stratum code of Koto is here at https://github.com/okoto-xyz/node-stratum-pool-koto
Yes, we had omitted the reservartion field in first release of Koto to make the size of blockheader 80. Therefore, to introduce Sampling functions, we have decided to add finalsaplinghash field to the blockheader.

**Pull request merged**
